name: Font Subsetting and Compression

on:
  push:
    branches:
      - main
    paths:
      - 'FortuneUpUp.js'

jobs:
  FontCompress:
    runs-on: ubuntu-latest
    if: github.actor != 'web-flow[bot]'
    steps:
      - name: Set up SSH key
        run: |
          sudo apt-get update && sudo apt-get install -y openssh-client
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install FontTools
        run: |
          pip install fonttools
          pip install Brotli
      - name: Download Font
        run: curl -L -o XiaolaiSC-Regular.ttf https://file.muspace.top/font/XiaolaiSC-Regular.ttf
      - name: Checkout Main Branch
        uses: actions/checkout@v2
        with:
          ref: main
          path: main
      - name: Checkout FontCompress Branch
        uses: actions/checkout@v2
        with:
          ref: FontCompress
          path: FontCompress
      - name: Copy Files
        run: |
          cp main/FortuneUpUp.js FontCompress/FortuneUpUp.js
          cp XiaolaiSC-Regular.ttf FontCompress/XiaolaiSC-Regular.ttf
      - name: Compress Fonts
        working-directory: FontCompress
        run: python Compress.py
      - name: Git push
        working-directory: FontCompress
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "noreply@github.com"
          git add .
          git commit -m "[Font Compress] ${{ github.event.head_commit.message }}"
          git push git@github.com:Moemu/FortuneUpUp.git HEAD:FontCompress